= Zi9's MapLoader map creation technical documentation
Zi9#3641
v1.1
:toc:

Zi9's Map Loader is a plugin for CarX Drift Racing Online, that enables community made maps to be loaded ingame like regular CarX maps. These maps are built within the Unity game engine and exported as AssetBundles.

== Requirements

For building maps you will need:

* Unity 2019.4.14f1
* Map Builder Utility (Zimap SDK) - Requires .NET Framework 4.7

== Making a map mod

First step is to create a new folder to keep all the needed files in. In this document we will use the name ``ModMap``.

=== Setting up the metadata

Create a new text file called ``meta.txt`` in this folder with the following content.

.meta.txt file content
----
This is where you change settings for the map
Do not change the structure of the file, Name must be the 4th line and so on

Name: Your Modded Map Name
----

Change the name to the map you will be making.

CAUTION: The name must only contain ASCII characters (A-Z a-z 0-9)

=== Generating an ID for your map

You can generate an ID using the MapBuilder.exe by just double-clicking on it, it will generate an id and save it in ``id.txt`` next to the executable. Move this into your map data folder.

=== Building the asset bundle

You will need to set your Unity project up for HDRP assets and your project should only contain 1 scene.

NOTE: Scripts are not supported for mod map scenes

The scene must only contain 1 root object called ``ModMapRoot``, all level GameObjects must be contained within the ``ModMapRoot`` GameObject. 

IMPORTANT: Your final map scene must have the id as its name

The map loader will look for GameObjects with the names that are listed below, all children of these objects will have drivable surfaces with phsyical properties added to it.

The following names are supported for physics material setup:

* road
* kerb
* sand
* snow
* grass
* gravel
* icyroad
* dirt

The loader will also look for a GameObject called ``spawnpoint``. This is where the player will spawn on game load, without a spawnpoint the player will spawn at (0, 0, 0).

.Example scene structure
----
1747620 (Scene)
└── ModMapRoot
   ├── houseModel
   ├── randomLevelGeometry
   ├── randomLevelGeometry2
   ├── randomLevelGeometry3
   ├── road
   │  ├── road_part1
   │  ├── road_part2
   │  └── road_part3
   ├── grass
   │  ├── grass1
   │  └── grass2
   └── spawnpoint
----

After exporting the asset bundle, you only need the file that has no file extension. Rename that to map.assetbundle and place it in your map data folder.

=== Adding the textures for UI

The map loader needs 4 textures for every custom map.

icon.png:: This is what is shown in the singleplayer track selection screen
loadscreen.png:: The loading screen background image
lobby.png:: The image that is shown when making a new multiplayer lobby
minimap.png:: Minimap image shown in the singleplayer track selection screen

Add these textures into your mod map folder.

NOTE: Keep texture sizes reasonable (a 1920x1080 icon doesn't make sense)

=== Ready to build

.The final folder structure for building a zimap file
----
your-map-folder
├── icon.png
├── id.txt
├── loadscreen.png
├── lobby.png
├── map.assetbundle
├── meta.txt
└── minimap.png
----

Make sure you are not missing any files or else the build process will fail.

=== Building the map using Zimap SDK

To build the map you just have to drag the whole map data folder onto the MapBuilder.exe icon and that will start the build process. If the process is succesful you should have a ``.zimap`` file in your map data folder.
